### ISSUE TITLE
Errors from Relaton

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/relaton#15]
Currently make all fails in `metanorma-gb` due to this error:

```
NoMethodError: undefined method `empty?' for #<IsoBibItem::IsoBibliographicItem:0x00007f7f8213e328>
/Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/relaton-0.2.6/lib/relaton/db.rb:167:in `new_bib_entry'
/Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/relaton-0.2.6/lib/relaton/db.rb:154:in `check_bibliocache'
```

In addition, fetching Relaton entries fail:

```
WARNING: no match found online for ISO 2382. The code must be exactly like it is on the standards website.
If you wanted to cite all document parts for the reference, use "ISO 2382 (all parts)".
If the document is not a standard, use its document type abbreviation (TS, TR, PAS, Guide).
fetching ISO 20004...
```

Can you please help fix this ASAP? Thanks!

cc: @opoudjis

**Comment by andrew2net** [comment]
@ronaldtse try now please

**Comment by andrew2net** [comment]
@ronaldtse try again, please

**Comment by ronaldtse** [comment]
@andrew2net it works! Thanks!!
